[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/__/auth/handler"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true
