[build]
  command = "npm run build"
  publish = "dist"

# ⚡ Manejo del redirect de Firebase Auth
[[redirects]]
  from = "/__/auth/handler"
  to = "/index.html"
  status = 200
  force = true

# ⚡ SPA fallback (todas las rutas van a index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
